[package]
name = "Onvif-IP-Camera-Mock"
version = "0.1.0"
edition = "2021"

[dependencies]
image = "0.25"
imageproc = "0.24"
ab_glyph = "0.2"
chrono = "0.4"
rand = "0.8"
tokio = { version = "1", features = ["full"] }